# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 567cca9f227c72175820fe55172756a7b9b543181daba0e9f3be425cee11ae1aea885d44a7005906cd6b1a9874d84867e144c32c21948afb94da66b55a9ce7eb

test:
  secret_key_base: e69c25495091b838ab85c843c3733951beefa72a3c8bafce3ab7d7007f305d5fcab7d0c2eaed6c77092d85d51580f6a62824c76e4dda2d5bd545c5330c0585cc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
